### ISSUE TITLE
Adding NEOPIXEL to board definitions

### ISSUE THREAD

**Issue by RetiredWizard** [solderparty/keyboard_featherwing_sw#5]
Just a suggestion really :)

I've added the following line to both my version of kfw_s2_board.py and kfw_pico_board.py which has allowed some of my generic RGB code to run:

NEOPIXEL = D11

This should obviously be added below the point where D11 is assigned :)

**Comment by arturo182** [comment]
Hmm, you're 100% right, I'm surprised I missed that myself! Any chance you could submit a PR?

**Comment by RetiredWizard** [comment]
Sure, I'll put it up later this afternoon.
